name: CI
on: pull_request

jobs:
  local-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: "13.x"

      - run: yarn
      - run: yarn docs-sync validate-against-en

  site-builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: "13.x"

      # Clone this PR, and setup the deps
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - run: yarn

      # Clone the TS website, basically:
      # git clone https://github.com/microsoft/TypeScript-Website website
      - name: Checkout tools repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          repository: microsoft/TypeScript-Website
          path: website

      # Both the microsoft/TypeScript-Website & 1 - don't really need to be there, but 
      # this migrates the translated docs into the website
      - run: yarn docs-sync pull microsoft/TypeScript-Website 1 --from-cwd . --to-cwd website

      # Get dependencies for building the ebooks
      - run: sudo apt-get update
      - run: sudo apt install calibre

      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore
        working-directory: ./website


      # Verify the website build
      - run: yarn bootstrap
        working-directory: ./website

      - run: yarn workspace typescriptlang-org build
        working-directory: ./website

      # Verify the website build
      - run: yarn test
        working-directory: ./website
